#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker666"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "8ce90606d63f49cab2b7e3f9a7e4414f" }
]

[assets]
directory = "./public"
